#! /usr/bin/env python3
import functions
import json
import re
import requests
import random

if __name__=="__main__":
    subscription_key = 'd50b235768634206b00dfc66816ea385'

    response = functions.getText(subscription_key, 'Recording.wav')
    if response.status_code==200:
        my_json = json.loads(response.content.decode('utf-8')) # .replace("'", '"')
        # my_json = response.content.decode("utf-8").replace("'", '"')
        # print(my_json)
        recognition_status = my_json['RecognitionStatus']
        # print(recognition_status)        
        if recognition_status=='Success':
            with open('output.txt', 'w') as out_file:
                out_file.write(my_json['DisplayText'])
    else:
        print("Speech to text")
        print(response.status_code)
        print(response.reason)

    text = ''

    with open('output.txt', 'r') as in_file:
        for line in in_file:
            text += line

    text = text.lower()

    if text.find('turn on the lights')!=-1:
        text = 'Hello darkness my old friend'
        # turns lights purple
        functions.displayColor(106, 0, 128)
    elif text.find('party time')!=-1:
        text = 'Can you really party alone? Ha, ha, ha. loser'
        # turns lights off
        functions.displayColor(0, 0, 0)
    elif text.find('time for bed')!=-1:
        text = 'Wake up!! No sleep for you!'
        # turns lights white
        functions.displayColor(255, 255, 255)
    elif text.find('turn off the lights')!=-1:
        text = 'Okay, turning off the lights'
        # turns lights off
        functions.displayColor(0, 0, 0)
    elif text.find('turn the lights green')!=-1:
        text = 'Okay, turning the lights green'
        # turns lights green
        functions.displayColor(0, 255, 0)
    elif text.find('turn the lights blue')!=-1:
        text = 'Okay, turning the lights blue'
        # turns lights blue
        functions.displayColor(0, 0, 255)
    elif text.find('turn the lights red')!=-1:
        text = 'Okay, turning the lights red'
        # turns lights red
        functions.displayColor(255, 0, 0)
    elif text.find('turn the lights')!=-1:
        match = re.search('turn the lights (\w+)', text)
        if match != None:
            text = 'I don\'t know how to turn the lights ' + match.groups()[0] + "."
        else:
            text = 'Sorry, I don\'t understand'
    elif text.find('tell ben a message')!=-1:
        x = random.randint(0, 2)
        if x == 0:
            text = 'Run away, I\'m Coming!'
        else:
            text = 'Ben, a Message'
    elif text.find('you suck alex')!=-1:
        text = 'Whoever said that, you\'re the one who sucks'
    elif text.find('notice me senpai')!=-1:
        text = 'Cricket, Cricket'
    else:
        text = 'Sorry, I don\'t understand'

    with open('input.txt','w') as out_file:
        out_file.write(text)

    response = functions.getSpeech(subscription_key, 'input.txt')
    if response.status_code==200:
        with open('response.wav', 'wb') as out_file:
            out_file.write(response.content)
    else:
        print('Text to speech:')
        print(response.status_code)
        print(response.reason)