#! /usr/bin/env python3

import functions
import json

if __name__=="__main__":
    subscription_key = 'd50b235768634206b00dfc66816ea385'
    response = functions.getText(subscription_key, 'Wake.wav')

    if response.status_code==200:
        my_json = json.loads(response.content.decode('utf-8')) # .replace("'", '"')
        # my_json = response.content.decode("utf-8").replace("'", '"')
        # print(my_json)
        recognition_status = my_json['RecognitionStatus']
        # print(recognition_status)        
        if recognition_status=='Success':
            text = my_json['DisplayText']
            
            text = text.lower()

            print(text)

            if text.find('hey alex')!=-1 or text.find('hey alice')!=-1:
                # success
                text = 'Alex here.'
                with open('input.txt','w') as out_file:
                    out_file.write(text)

                response = functions.getSpeech(subscription_key, 'input.txt')
                if response.status_code==200:
                    with open('alex.wav', 'wb') as out_file:
                        out_file.write(response.content)
                else:
                    print('Text to speech:')
                    print(response.status_code)
                    print(response.reason)
                exit(0)
            
        else:
            print("bad speech to text")
    else:
        print("Speech to text")
        print(response.status_code)
        print(response.reason)

exit(1)